version: '3'

services:
  database:
    image: 'mysql:8.0'
    container_name: db_terrapp
    volumes:
      - '.:/var/www/html/app'
    environment:
      - MYSQL_DATABASE=terrapp
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306:3306'