parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/User/DomainModel/'

    App\User\Application\Command\DataToCreateUserHandler:
        tags:
            - { name: messenger.message_handler }

    App\Animal\Infrastructure\AnimalDbRepository:
        autowire: true

    App\Animal\DomainModel\AnimalRepository:
        class: 'App\Animal\Infrastructure\AnimalDbRepository'

    App\Animal\Application\AnimalService:
        arguments:
            $animalRepository: '@App\Animal\DomainModel\AnimalRepository'
